"""empty message

Revision ID: 36247dc133f7
Revises: 7627eb4cdfdf
Create Date: 2020-01-28 06:21:40.623204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36247dc133f7'
down_revision = '7627eb4cdfdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('email1', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'person', ['email1'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'person', type_='unique')
    op.drop_column('person', 'email1')
    # ### end Alembic commands ###
